THICKNESS = 3;
DIAMETER = 50;
BEARING_INNER_DIAMETER = 11.5;
BEARING_LIP_DIAMETER = BEARING_INNER_DIAMETER + 4;
BEARING_LIP_THICKNESS = 1;
BEARING_THICKNESS = 12;

$fn = 100;

union() {
    cylinder(h = THICKNESS, d = DIAMETER);
    cylinder(h = THICKNESS+BEARING_LIP_THICKNESS, d = BEARING_LIP_DIAMETER);
    cylinder(h = THICKNESS + BEARING_THICKNESS, d = BEARING_INNER_DIAMETER);
}
