SWITCH_WIDTH = 17;
SWITCH_LENGTH = 29;
SWITCH_THICKNESS = 12;
SWITCH_OFFSET_X = 1.5;
SWITCH_OFFSET_Y = 1.5;

SWITCH_CONNECTOR_WIDTH = 22;
SWITCH_CONNECTOR_LENGTH = 38;
SWITCH_CONNECTOR_OFFSET_X = 3;
SWITCH_CONNECTOR_OFFSET_Y = 8;

SWITCH_BUTTON_WIDTH = 15;
SWITCH_BUTTON_LENGTH = 30;
SWITCH_BUTTON_OFFSET_X = -15;
SWITCH_BUTTON_OFFSET_Y = -15;

MOUNT_HOLE_OFFSET_X = SWITCH_WIDTH-3;
MOUNT_HOLE_OFFSET_Y = 4;
MOUNT_HOLE_SPACING_X = 11;
MOUNT_HOLE_SPACING_Y = 22;
MOUNT_HOLE_DIA = 3.5;

WALL_THICKNESS = 1.5;
WIDTH = SWITCH_WIDTH + 2 * WALL_THICKNESS + 10;
LENGTH = SWITCH_LENGTH + 2 * WALL_THICKNESS + 15;
THICKNESS = SWITCH_THICKNESS + WALL_THICKNESS;

$fn = 50;

module switch() {
  cube(size = [SWITCH_WIDTH, SWITCH_LENGTH, SWITCH_THICKNESS]);

  translate([SWITCH_CONNECTOR_OFFSET_X, SWITCH_CONNECTOR_OFFSET_Y, 0])
  cube(size = [SWITCH_CONNECTOR_WIDTH, SWITCH_CONNECTOR_LENGTH, SWITCH_THICKNESS]);

  translate([SWITCH_BUTTON_OFFSET_X, SWITCH_BUTTON_OFFSET_Y, 0])
  cube(size = [SWITCH_BUTTON_WIDTH, SWITCH_BUTTON_LENGTH, SWITCH_THICKNESS]);

  for(i = [0, 1]) {
    translate([-i * MOUNT_HOLE_SPACING_X + MOUNT_HOLE_OFFSET_X, i * MOUNT_HOLE_SPACING_Y + MOUNT_HOLE_OFFSET_Y, 0])
    cylinder(d = MOUNT_HOLE_DIA, h = THICKNESS);
  }
}

module cover() {
  difference() {
    cube(size = [WIDTH, LENGTH, THICKNESS]);

    #translate([SWITCH_OFFSET_X, SWITCH_OFFSET_Y, 0])
    switch();
  }
}

cover();
